#!/bin/sh

set -e

cd "$(dirname $0)"
RELEASE_PATH="$(pwd)"

embeddedScript="default"
embeddedScript="testing"

TRUST=$(echo $(find "$(pwd)"/trust/*.pem "$(pwd)"/trust/*.cer "$(pwd)"/trust/*.crt 2>/dev/null) | tr ' ' ',')

machineType=$(uname -m)
bin=bin
efibin=bin
buildLkrn=
buildIso=
buildUsb=
buildEfi=1
efiout=
case "$machineType" in
  x86_64)
    bin=bin
    buildLkrn=1
    buildIso=1
    efibin=bin-x86_64-efi
    efiout=bootx64.efi
    ;;
  aarch64)
    bin=bin-arm64-efi
    efibin="$bin"
    efiout=bootaa64.efi
    #buildUsb=1
    ;;
  *)
    echo "Unknown machine type: $machineType" >&2
    exit 1
esac

[ -n "$buildLkrn" ] && ( cd ipxe/src ; make CERT="$TRUST" TRUST="$TRUST" $bin/ipxe.lkrn && cp $bin/ipxe.lkrn "$RELEASE_PATH"/ipxe-${machineType}.lkrn )
[ -n "$buildIso" ] && ( cd ipxe/src ; make EMBED="$RELEASE_PATH/${embeddedScript}.ipxe" CERT="$TRUST" TRUST="$TRUST" $bin/ipxe.iso && cp $bin/ipxe.iso "$RELEASE_PATH"/ipxe-${machineType}.iso )
[ -n "$buildUsb" ] && ( cd ipxe/src ; make EMBED="$RELEASE_PATH/${embeddedScript}.ipxe" CERT="$TRUST" TRUST="$TRUST" $bin/ipxe.usb && cp $bin/ipxe.usb "$RELEASE_PATH"/ipxe-${machineType}.usb )
[ -n "$buildEfi" ] && ( cd ipxe/src ; make EMBED="$RELEASE_PATH/${embeddedScript}.ipxe" CERT="$TRUST" TRUST="$TRUST" $efibin/ipxe.efi && cp $efibin/ipxe.efi "$RELEASE_PATH"/ipxe-${machineType}.efi )
[ -n "$buildEfi" ] && ( cd ipxe/src ; make EMBED="$RELEASE_PATH/${embeddedScript}.ipxe" CERT="$TRUST" TRUST="$TRUST" $efibin/snp.efi && cp $efibin/snp.efi "$RELEASE_PATH"/snp-${machineType}.efi )

if [[ -n "$efiout" ]]; then
  efibootOut="efi-boot-image/EFI/BOOT"
  mkdir -p "$efibootOut"
  cp -av "$RELEASE_PATH"/ipxe-${machineType}.efi "$efibootOut/$efiout"
fi


echo "DONE!"
