#!/bin/sh

set -e

cd "$(dirname $0)"
RELEASE_PATH="$(pwd)"

embeddedScript="default"
embeddedScript="testing"

TRUST=$(echo $(find "$(pwd)"/trust/*.pem "$(pwd)"/trust/*.cer "$(pwd)"/trust/*.crt 2>/dev/null) | tr ' ' ',')

machineType=$(uname -m)
bin=bin
buildLkrn=
buildIso=
buildUsb=
buildEfi=1
case "$machineType" in
  x86_64)
    bin=bin
    buildLkrn=1
    buildIso=1
    ;;
  aarch64)
    bin=bin-arm64-efi
    #buildUsb=1
    ;;
  *)
    echo "Unknown machine type: $machineType" >&2
    exit 1
esac

[ -n "$buildLkrn" ] && ( cd ipxe/src ; make CERT="$TRUST" TRUST="$TRUST" $bin/ipxe.lkrn && cp $bin/ipxe.lkrn "$RELEASE_PATH"/ipxe-${machineType}.lkrn )
[ -n "$buildIso" ] && ( cd ipxe/src ; make EMBED="$RELEASE_PATH/${embeddedScript}.ipxe" CERT="$TRUST" TRUST="$TRUST" $bin/ipxe.iso && cp $bin/ipxe.iso "$RELEASE_PATH"/ipxe-${machineType}.iso )
[ -n "$buildUsb" ] && ( cd ipxe/src ; make EMBED="$RELEASE_PATH/${embeddedScript}.ipxe" CERT="$TRUST" TRUST="$TRUST" $bin/ipxe.usb && cp $bin/ipxe.usb "$RELEASE_PATH"/ipxe-${machineType}.usb )
[ -n "$buildEfi" ] && ( cd ipxe/src ; make EMBED="$RELEASE_PATH/${embeddedScript}.ipxe" CERT="$TRUST" TRUST="$TRUST" $bin/ipxe.efi && cp $bin/ipxe.efi "$RELEASE_PATH"/ipxe-${machineType}.efi )
[ -n "$buildEfi" ] && ( cd ipxe/src ; make EMBED="$RELEASE_PATH/${embeddedScript}.ipxe" CERT="$TRUST" TRUST="$TRUST" $bin/snp.efi && cp $bin/snp.efi "$RELEASE_PATH"/snp-${machineType}.efi )

echo "DONE!"
