#!/bin/sh
#
# NOTE: This script assumes that you're running Alpine Linux
#

cd "$(dirname $0)"
apk add \
	git build-base perl xz-dev coreutils \
	bash cdrkit mtools
apk add syslinux

git submodule init
git submodule update

( cd ipxe ; ln -s /usr/share/syslinux/isolinux.bin . )

ln -sf ../../../../local-config.h ipxe/src/config/local/general.h

cd trust
wget -O ipxe-root-ca.crt https://ipxe.org/_media/certs/ca.crt
wget -O alpine-netboot-ca.crt https://git.alpinelinux.org/aports/plain/main/alpine-ipxe/alpine-netboot-ca.crt
wget -O DST_Root_CA_X3.pem https://git.alpinelinux.org/aports/plain/main/alpine-ipxe/DST_Root_CA_X3.pem
